---
# Copyright (C) 2016 iNuron NV
#
# This file is part of Open vStorage Open Source Edition (OSE),
# as available from
#
#      http://www.openvstorage.org and
#      http://www.openvstorage.com.
#
# This file is free software; you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License v3 (GNU AGPLv3)
# as published by the Free Software Foundation, in version 3 as it comes
# in the LICENSE.txt file of the Open vStorage OSE distribution.
#
# Open vStorage is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY of any kind.

- hosts: datacenters
  gather_facts: false

  tasks:
  - name: execute task based on dc filter
    template:
      src=latency.sh.j2
      dest=/root/latency.sh
      owner=root
      group=root
      mode=744
    when: "'dc' in '{{ item }}'"
    with_items: "{{ hostvars[inventory_hostname].group_names }}"
    register: mylist

  - name: execute script
    shell: bash /root/latency.sh
